FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /sports_diary

COPY ..
RUN dotnet restore "./SportsDiary/SportsDiary.csprog" --disable-parallel
RUN dotnet publish "./SportsDiary/SportsDiary.csprog" -c Release -o /app --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build-env /app ./
EXPOSE 5000
ENTRYPOINT ["dotnet", "SportsDiary.dll"]
