FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /source

COPY *.sln .
COPY SportsDiary/*.csproj ./SportsDiary/
RUN dotnet restore

COPY SportsDiary/. ./SportsDiary/
WORKDIR /source/SportsDiary
RUN dotnet publish -c Release -o /app --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build-env /app ./
EXPOSE 8080
ENTRYPOINT ["dotnet", "SportsDiary.dll"]
